/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Header that contains the code (mostly headers) for which Rust bindings
 * will be automatically generated by `bindgen`.
 *
 * Sorted alphabetically.
 */

#include <kunit/test.h>
#include <linux/amba/bus.h>
#include <linux/device.h>
#include <linux/cdev.h>
#include <linux/clk.h>
#include <linux/errname.h>
#include <linux/file.h>
#include <linux/fs.h>
#include <linux/fs_parser.h>
#include <linux/gpio/driver.h>
#include <linux/hw_random.h>
#include <linux/interrupt.h>
#include <linux/io.h>
#include <linux/io-pgtable.h>
#include <linux/iosys-map.h>
#include <linux/irqdomain.h>
#include <linux/irq.h>
#include <linux/ktime.h>
#include <linux/miscdevice.h>
#include <linux/mm.h>
#include <linux/module.h>
#include <linux/netfilter_arp.h>
#include <linux/netfilter.h>
#include <linux/netfilter_ipv4.h>
#include <linux/netfilter_ipv6.h>
#include <linux/of.h>
#include <linux/of_address.h>
#include <linux/of_platform.h>
#include <linux/platform_device.h>
#include <linux/pm.h>
#include <linux/pm_domain.h>
#include <linux/poll.h>
#include <linux/random.h>
#include <linux/security.h>
#include <linux/slab.h>
#include <linux/soc/apple/rtkit.h>
#include <linux/sysctl.h>
#include <linux/timekeeping.h>
#include <linux/uaccess.h>
#include <linux/uio.h>
#include <linux/xarray.h>
#include <uapi/asm-generic/ioctl.h>
#include <uapi/linux/android/binder.h>

/* `bindgen` gets confused at certain things. */
const gfp_t BINDINGS_GFP_KERNEL = GFP_KERNEL;
const gfp_t BINDINGS___GFP_ZERO = __GFP_ZERO;
const __poll_t BINDINGS_EPOLLIN = EPOLLIN;
const __poll_t BINDINGS_EPOLLOUT = EPOLLOUT;
const __poll_t BINDINGS_EPOLLERR = EPOLLERR;
const __poll_t BINDINGS_EPOLLHUP = EPOLLHUP;

const loff_t BINDINGS_MAX_LFS_FILESIZE = MAX_LFS_FILESIZE;

const u32 BINDINGS_DL_FLAG_STATELESS = DL_FLAG_STATELESS;
const u32 BINDINGS_DL_FLAG_AUTOREMOVE_CONSUMER = DL_FLAG_AUTOREMOVE_CONSUMER;
const u32 BINDINGS_DL_FLAG_PM_RUNTIME = DL_FLAG_PM_RUNTIME;
const u32 BINDINGS_DL_FLAG_RPM_ACTIVE = DL_FLAG_RPM_ACTIVE;
const u32 BINDINGS_DL_FLAG_AUTOREMOVE_SUPPLIER = DL_FLAG_AUTOREMOVE_SUPPLIER;
const u32 BINDINGS_DL_FLAG_AUTOPROBE_CONSUMER = DL_FLAG_AUTOPROBE_CONSUMER;
const u32 BINDINGS_DL_FLAG_MANAGED = DL_FLAG_MANAGED;
const u32 BINDINGS_DL_FLAG_SYNC_STATE_ONLY = DL_FLAG_SYNC_STATE_ONLY;
const u32 BINDINGS_DL_FLAG_INFERRED = DL_FLAG_INFERRED;

const gfp_t BINDINGS_XA_FLAGS_LOCK_IRQ = XA_FLAGS_LOCK_IRQ;
const gfp_t BINDINGS_XA_FLAGS_LOCK_BH = XA_FLAGS_LOCK_BH;
const gfp_t BINDINGS_XA_FLAGS_TRACK_FREE = XA_FLAGS_TRACK_FREE;
const gfp_t BINDINGS_XA_FLAGS_ZERO_BUSY = XA_FLAGS_ZERO_BUSY;
const gfp_t BINDINGS_XA_FLAGS_ALLOC_WRAPPED = XA_FLAGS_ALLOC_WRAPPED;
const gfp_t BINDINGS_XA_FLAGS_ACCOUNT = XA_FLAGS_ACCOUNT;
const gfp_t BINDINGS_XA_FLAGS_ALLOC = XA_FLAGS_ALLOC;
const gfp_t BINDINGS_XA_FLAGS_ALLOC1 = XA_FLAGS_ALLOC1;

const xa_mark_t BINDINGS_XA_MARK_0 = XA_MARK_0;
const xa_mark_t BINDINGS_XA_MARK_1 = XA_MARK_1;
const xa_mark_t BINDINGS_XA_MARK_2 = XA_MARK_2;
const xa_mark_t BINDINGS_XA_PRESENT = XA_PRESENT;
const xa_mark_t BINDINGS_XA_MARK_MAX = XA_MARK_MAX;
const xa_mark_t BINDINGS_XA_FREE_MARK = XA_FREE_MARK;
